version: "3.9"

services:
  library:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    volumes:
      - ./data:/app-data

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-library_service}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME:-admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD:-pass}
    depends_on:
      - mongo